{
"@R":"1369621309",
"eredirect":"",
"redirect":"",
"pre_action":"",
"post_action":"",
"session_exp":"2147483647",
"expires":"",
"header":"",
"pheader":"",
"bottom":"",
"layout":{
"type":"JsonWidget",
"class":"",
"height":"",
"width":"",
"min_height":"",
"min_width":"",
"extra":"",
"component":"component://wiki2-component/default/pages/edit_action",
"children":[

]
},
"_u":"edit_action"
}