{
"@R":"1372044674",
"eredirect":"",
"redirect":"",
"pre_action":"",
"post_action":"",
"session_exp":"2147483647",
"expires":"",
"header":"<meta name=\"description\" content=\"\">\r
",
"pheader":"",
"bottom":"",
"layout":{
"type":"HorizontalWidget",
"class":"",
"height":"",
"width":"",
"min_height":"",
"min_width":"",
"extra":"",
"component":"component://core-component/default/horizontal",
"children":[
{
"type":"HorizontalWidget",
"class":"",
"height":"",
"width":"",
"min_height":"",
"min_width":"",
"extra":"",
"component":"component://core-component/default/utils/wikipage",
"children":[

]
},
{
"type":"HorizontalWidget",
"class":"",
"height":"",
"width":"",
"min_height":"",
"min_width":"",
"extra":"",
"component":"component://test-component/default/page",
"children":[

]
}
]
},
"_u":"main"
}