{
"@R":"1369623224",
"type":"JsonWidget",
"subject":"pages/edit_action",
"description":"",
"css":"",
"js":"",
"id":"",
"class":"",
"body":"A.wiki2\r
",
"action":[
"action://wiki2-action/wiki2/PageAction?set"
],
"header":"",
"bottom":"",
"_u":"pages/edit_action"
}